import type { VowlJson } from './types';

// Sample WeftOS ontology for testing the navigator.
export const sampleOntology: VowlJson = {
  header: {
    title: 'WeftOS Kernel Ontology',
    iri: 'https://weftos.weavelogic.ai/ontology/kernel',
    version: '0.6.11',
    description: 'Core concepts of the WeftOS AI kernel',
  },
  metrics: {
    classCount: 12,
    objectPropertyCount: 10,
    datatypePropertyCount: 3,
    individualCount: 0,
  },
  class: [
    { id: 'c0', type: 'owl:Class' },
    { id: 'c1', type: 'owl:Class' },
    { id: 'c2', type: 'owl:Class' },
    { id: 'c3', type: 'owl:Class' },
    { id: 'c4', type: 'owl:Class' },
    { id: 'c5', type: 'owl:Class' },
    { id: 'c6', type: 'owl:Class' },
    { id: 'c7', type: 'owl:Class' },
    { id: 'c8', type: 'rdfs:Datatype' },
    { id: 'c9', type: 'rdfs:Datatype' },
    { id: 'c10', type: 'owl:Class' },
    { id: 'c11', type: 'owl:Class' },
  ],
  classAttribute: [
    { id: 'c0', label: { en: 'Kernel' }, description: 'WeftOS kernel — boot, process table, services', instances: 1 },
    { id: 'c1', label: { en: 'Agent' }, description: 'An autonomous agent managed by the kernel', instances: 8 },
    { id: 'c2', label: { en: 'Process' }, description: 'A running process in the kernel process table' },
    { id: 'c3', label: { en: 'Service' }, description: 'A registered kernel service' },
    { id: 'c4', label: { en: 'Plugin' }, description: 'A WASM plugin loaded into the sandbox' },
    { id: 'c5', label: { en: 'Memory' }, description: 'Persistent agent memory (long-term + working)' },
    { id: 'c6', label: { en: 'ECC Model' }, description: 'Evolving Causal Cognition model' },
    { id: 'c7', label: { en: 'Resource' }, description: 'A node in the exo-resource tree' },
    { id: 'c8', label: { en: 'AgentId' }, description: 'UUID identifier for an agent' },
    { id: 'c9', label: { en: 'Capability' }, description: 'Permission capability set' },
    { id: 'c10', label: { en: 'Sandbox' }, description: 'WASM execution sandbox with capability constraints' },
    { id: 'c11', label: { en: 'IPC Topic' }, description: 'Pub/sub message topic for inter-process communication' },
  ],
  property: [
    { id: 'p0', type: 'owl:ObjectProperty' },
    { id: 'p1', type: 'owl:ObjectProperty' },
    { id: 'p2', type: 'owl:ObjectProperty' },
    { id: 'p3', type: 'owl:ObjectProperty' },
    { id: 'p4', type: 'owl:ObjectProperty' },
    { id: 'p5', type: 'owl:ObjectProperty' },
    { id: 'p6', type: 'owl:ObjectProperty' },
    { id: 'p7', type: 'rdfs:subClassOf' },
    { id: 'p8', type: 'owl:DatatypeProperty' },
    { id: 'p9', type: 'owl:ObjectProperty' },
    { id: 'p10', type: 'owl:ObjectProperty' },
    { id: 'p11', type: 'owl:ObjectProperty' },
    { id: 'p12', type: 'owl:ObjectProperty' },
  ],
  propertyAttribute: [
    { id: 'p0', domain: 'c0', range: 'c2', label: { en: 'manages' } },
    { id: 'p1', domain: 'c0', range: 'c3', label: { en: 'hosts' } },
    { id: 'p2', domain: 'c1', range: 'c2', label: { en: 'runsAs' } },
    { id: 'p3', domain: 'c1', range: 'c5', label: { en: 'hasMemory' } },
    { id: 'p4', domain: 'c1', range: 'c4', label: { en: 'loads' } },
    { id: 'p5', domain: 'c4', range: 'c10', label: { en: 'executesIn' } },
    { id: 'p6', domain: 'c1', range: 'c6', label: { en: 'hasCognition' } },
    { id: 'p7', domain: 'c2', range: 'c1', label: { en: 'subClassOf' } },
    { id: 'p8', domain: 'c1', range: 'c8', label: { en: 'hasId' } },
    { id: 'p9', domain: 'c10', range: 'c9', label: { en: 'enforces' } },
    { id: 'p10', domain: 'c7', range: 'c7', label: { en: 'childOf' } },
    { id: 'p11', domain: 'c1', range: 'c11', label: { en: 'subscribesTo' } },
    { id: 'p12', domain: 'c0', range: 'c7', label: { en: 'ownsTree' } },
  ],
};
